# Generated by Django 3.1.1 on 2020-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
