# Generated by Django 3.1.1 on 2020-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0002_carinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='mileage',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
