# Generated by Django 3.1.1 on 2020-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('customernumber', models.IntegerField(null=True)),
                ('emailid', models.EmailField(max_length=60, null=True)),
                ('model', models.CharField(max_length=60)),
                ('fueltype', models.CharField(max_length=60)),
                ('servicetype', models.CharField(blank=True, max_length=60)),
                ('timeslot', models.DateTimeField()),
            ],
        ),
    ]
