# Generated by Django 3.1.1 on 2020-09-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapi', '0002_customerinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='price',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='carprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
